### ISSUE TITLE
Uncaught (in promise) Error: [PADDLE] Unknown option parameter 'vendor'

### ISSUE THREAD

**Issue by pushkarsingh32** [chargekit/paddle#8] opened 2024-01-14 07:28 UTC
```js
    const PaymentPageClient = () => {
    const [yearly, setYearly] = useState(true);
    const [loading, setLoading] = useState({});
    const { session: supabaseSession } = useAuth();
    // const router = useRouter();
    // router.prefetch('/thank-you');

    const customerEmail = supabaseSession?.user?.email;
    const userId = supabaseSession?.user?.id;
    let [paddle, setPaddle] = useState(null);

    console.log("PaymentPageClient paddle: ", paddle);

    useEffect(() => {
        const clientSideToken = process.env.NEXT_PUBLIC_CLIENT_SIDE_TOKEN;
        loadScript().then((Paddle) => {
            Paddle.Environment.set("sandbox");
            Paddle.Setup({
                token: clientSideToken,
                vendor: process.env.NEXT_PUBLIC_PADDLE_SANDBOX_VENDOR_ID,
                checkout: {
                    settings: {
                        displayMode: "overlay",
                        theme: "light",
                        locale: "en",
                        allowLogout: false,
                        showAddDiscounts: false,
                    },
                },
                eventCallback: function (data) {
                    if (data?.name === "checkout.closed") {
                        setLoading({});
                    }
                }

            });
            setPaddle(Paddle);
            // // if paddle is null then setPaddle to Paddle
            // if (!paddle) {
            //     setPaddle(Paddle);
            // }
        });
    }, [setPaddle]);

    return (
        <div className=''>
            <PricingToggle yearly={yearly} setYearly={setYearly} />
            <PricingGrid yearly={yearly} paddle={paddle} customerEmail={customerEmail}
                userId={userId} loading={loading} setLoading={setLoading} />
        </div>
    )
}

export default PaymentPageClient;
```

The code works fine when I first visit other pages on the app then come back to the payment page. 

however when I go to payment page first it doesn't load Paddle & gives error for vendor id paddle.js:

```
1  Uncaught (in promise) Error: [PADDLE] Unknown option parameter 'vendor'
    at e.set (paddle.js:1:5676)
    at t.Setup (paddle.js:1:44889)
```

in below line

```
    return e.prototype.set = function(t) {
                if ("object" != typeof t)
                    throw new Error("[PADDLE] The Options() method accepts an object of options values.");
                for (var e in this.validateSeller(t.seller, t.token),
                t) {
                    if (!this.options.hasOwnProperty(e))
                        throw new Error("[PADDLE] Unknown option parameter '" + e + "'");
                    this.options[e] = t[e],
                    I.log("Set option '" + e + "' to '" + t[e] + "'.")
                }
            }
```
            
  However on repeat visit it doesn't show any error. 
  
  Any idea on this why this behaviour is happening?

**Comment by kossnocorp** [comment] 2024-01-15 08:41
> however when I go to payment page first it doesn't load Paddle & gives error for vendor id paddle.js:

I can't see any issues with how the Paddle script loaded, but I have a suspicion that it might be caused by Next.js rendering the page on the server. When you navigate from page to page, it happens on the client, hence the discrepancy.

However, I think the core of the problem is that `vendor` is not used (see docs; it's missing: https://developer.paddle.com/paddlejs/methods/paddle-setup). Try removing it, hopefully it will fix the problem.

Closing unless we found a bug in the library

**Closed as not planned by kossnocorp** 2024-01-15 08:41 UTC
